language: go
go_import_path: github.com/Ticketmaster/kubernetes-usage-log
sudo: false

go:
  - 1.8

notifications:
  on_success: never
  on_failure: never

script:
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOARM=6 go build -a -installsuffix cgo -ldflags '-w' 
